name: infra_prod

on:
  push:
    branches: ["dev"]
    paths:
      - "infra/envs/prod/**"
      - ".github/workflows/infra_prod.yml"

permissions:
  id-token: write
  contents: read

jobs:
  infra_prod_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::608145123666:role/project1-serverless-infra-prod
          aws-region: ap-south-1

      - name: Terraform Init & Plan (prod)
        run: |
          cd infra/envs/prod
          terraform init
          terraform plan -out=tfplan

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/envs/prod/tfplan

  infra_prod_apply:
    needs: [infra_prod_plan] 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::608145123666:role/project1-serverless-infra-prod
          aws-region: ap-south-1

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/envs/prod

      - name: Terraform init & apply (prod)
        run: |
          cd infra/envs/prod
          terraform init
          terraform apply -auto-approve tfplan
