name: infra-dev

on:
  push:
    branches: ["dev"]
    paths:
      - "infra/envs/dev/**"      # only run when infra files change
      - ".github/workflows/infra_dev.yml"

permissions:
  id-token: write        # <<< REQUIRED for OIDC
  contents: read   

jobs:
  infra_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::608145123666:role/github-infra-dev
          aws-region: ap-south-1

      - name: Terraform Init & Apply (dev)
        run: |
          cd infra/envs/dev
          terraform init
          terraform plan -out=tfplan
          # Auto-approval is enabled for the dev environment to streamline CI/CD and avoid manual intervention.
          terraform apply -auto-approve tfplan

